In [1]:
import pandas as pd

In [ ]:
# Attribute Information:
#    1. name	Name of the country concerned
#    2. landmass	1=N.America, 2=S.America, 3=Europe, 4=Africa, 4=Asia, 6=Oceania
#    3. zone	Geographic quadrant, based on Greenwich and the Equator
#                 1=NE, 2=SE, 3=SW, 4=NW
#    4. area	in thousands of square km
#    5. population	in round millions
#    6. language 1=English, 2=Spanish, 3=French, 4=German, 5=Slavic, 6=Other 
#                Indo-European, 7=Chinese, 8=Arabic, 
#                9=Japanese/Turkish/Finnish/Magyar, 10=Others
#    7. religion 0=Catholic, 1=Other Christian, 2=Muslim, 3=Buddhist, 4=Hindu,
#                5=Ethnic, 6=Marxist, 7=Others
#    8. bars     Number of vertical bars in the flag
#    9. stripes  Number of horizontal stripes in the flag
#   10. colours  Number of different colours in the flag
#   11. red      0 if red absent, 1 if red present in the flag
#   12. green    same for green
#   13. blue     same for blue
#   14. gold     same for gold (also yellow)
#   15. white    same for white
#   16. black    same for black
#   17. orange   same for orange (also brown)
#   18. mainhue  predominant colour in the flag (tie-breaks decided by taking
#                the topmost hue, if that fails then the most central hue,
#                and if that fails the leftmost hue)
#   19. circles  Number of circles in the flag
#   20. crosses  Number of (upright) crosses
#   21. saltires Number of diagonal crosses
#   22. quarters Number of quartered sections
#   23. sunstars Number of sun or star symbols
#   24. crescent 1 if a crescent moon symbol present, else 0
#   25. triangle 1 if any triangles present, 0 otherwise
#   26. icon     1 if an inanimate image present (e.g., a boat), otherwise 0
#   27. animate  1 if an animate image (e.g., an eagle, a tree, a human hand)
#                present, 0 otherwise
#   28. text     1 if any letters or writing on the flag (e.g., a motto or
#                slogan), 0 otherwise
#   29. topleft  colour in the top-left corner (moving right to decide 
#                tie-breaks)
#   30. botright Colour in the bottom-left corner (moving left to decide 
#                tie-breaks)

In [4]:
flag_data = pd.read_csv("flags.csv", names=['name', 'landmass', 'zone', 'area', 'population', 'language', 'religion', 'bars', 'stripes', 'colors', 'red', 'green', 'blue', 'gold', 'white', 'black', 'orange', 'mainhue', 'circles', 'crosses', 'saltires', 'quarters', 'sunstars', 'crescent', 'triangle', 'icon', 'animate', 'text', 'topleft', 'botright'])
flag_data

,name,landmass,zone,area,population,language,religion,bars,stripes,colors,...,saltires,quarters,sunstars,crescent,triangle,icon,animate,text,topleft,botright
0,Afghanistan,5,1,648,16,10,2,0,3,5,...,0,0,1,0,0,1,0,0,black,green
1,Albania,3,1,29,3,6,6,0,0,3,...,0,0,1,0,0,0,1,0,red,red
2,Algeria,4,1,2388,20,8,2,2,0,3,...,0,0,1,1,0,0,0,0,green,white
3,American-Samoa,6,3,0,0,1,1,0,0,5,...,0,0,0,0,1,1,1,0,blue,red
4,Andorra,3,1,0,0,6,0,3,0,3,...,0,0,0,0,0,0,0,0,blue,red
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,Western-Samoa,6,3,3,0,1,1,0,0,3,...,0,1,5,0,0,0,0,0,blue,red
190,Yugoslavia,3,1,256,22,6,6,0,3,4,...,0,0,1,0,0,0,0,0,blue,red
191,Zaire,4,2,905,28,10,5,0,0,4,...,0,0,0,0,0,1,1,0,green,green
192,Zambia,4,2,753,6,10,5,3,0,4,...,0,0,0,0,0,0,1,0,green,brown
193,Zimbabwe,4,2,391,8,10,5,0,7,5,...,0,0,1,0,1,1,1,0,green,green